msrv = "1.90"

cognitive-complexity-threshold = 3
too-many-arguments-threshold = 4
type-complexity-threshold = 80
large-error-threshold = 16
too-many-lines-threshold = 100
avoid-breaking-exported-api = true
enum-variant-size-threshold = 16
struct-field-name-threshold = 3
single-char-binding-names-threshold = 2
array-size-threshold = 512
trivial-copy-size-limit = 8